### PR TITLE
added font into repository

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by cbrewster** [comment]
Hi thanks for the pull request, is there a license we need to add in order to use this font?

**Comment by adamnemecek** [comment]
It's released under the Ubuntu Font License https://design.ubuntu.com/font/ which has it's own license https://ubuntu.com/legal/font-licence. Want to use a different font?

**Comment by cbrewster** [comment]
I'm okay with using this font, we just need to also add a file in the repo that contains the Ubuntu Font License

**Comment by adamnemecek** [comment]
Ok, added.

**Comment by cbrewster** [comment]
Thank you very much! 😄

**Comment by adamnemecek** [comment]
De nada.

**Pull request merged**
